(function attachEngine(root, factory) {
  const api = factory(root.DepotData, root.DepotMap, root.DepotUI);
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.DepotEngine = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createEngine(data, map, ui) {
  'use strict';
  const game={running:false,procedure:'Issue',mode:'learn',difficulty:'medium',mission:'campaign',role:'iv1',staticUnit:false,receiptHasDuesOut:false,transport:'Road',route:[],campaignStages:[],characterStages:[],index:0,score:0,combo:0,lives:3,elapsed:0,penalty:0,startedAt:0,cargo:{name:'None',icon:'📄',state:'Mission not started'},completed:[],mistakes:0,player:{x:570,y:590,r:16,speed:360,facing:1,moving:false},currentSpeed:360,boosting:false,trail:[],trailClock:0,keys:{},touchVector:{x:0,y:0},autoNavigation:null,situationGateKey:null,sound:true,lastTime:0,paused:false,selectedItem:'Generator Starter',selectionLocation:'Shed B / Rack 3'};
  let audioContext=null;

  function tone(frequency=500,duration=.08,type='sine',gain=.04){if(!game.sound)return;try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),volume=audioContext.createGain();oscillator.type=type;oscillator.frequency.value=frequency;volume.gain.value=gain;oscillator.connect(volume);volume.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}catch(error){/* Sound is optional. */}}
  function generateRoute(){if(game.mission==='campaign'){const campaign=data.campaigns[game.procedure==='Receipt'?'receiptNormal':'issueNormal'];game.campaignStages=campaign.stages.map(stage=>({...stage}));game.characterStages=[];game.route=game.campaignStages.map(stage=>stage.office)}else{game.campaignStages=[];game.route=[...data.routes[game.role]];game.characterStages=(data.characterStageEvents?.[game.role]||[]).map(stage=>({...stage}));if(['demand','irpsDuplicate'].includes(game.role)&&game.staticUnit)game.route=game.route.filter(id=>id!=='ULC');if(game.role==='receiptVoucher1'&&!game.receiptHasDuesOut){game.route=[...data.receiptRouteVariants.receiptVoucher1NoDuesOut];game.characterStages=game.characterStages.filter((stage,index)=>data.routes.receiptVoucher1[index]!=='FPVRelease')}}}
  function roleCargo(){const character=data.characters.find(item=>item.id===game.role);return{name:character.name,icon:character.icon,state:character.state||character.finalDisposition||'Source-backed Issue entity'}}
  function setCargoForStep(){if(game.mission==='campaign'){const stage=game.campaignStages[game.index];game.cargo={name:stage.focus,icon:map.building(stage.office,game.procedure).icon,state:stage.state}}else game.cargo=roleCargo();ui.updateCargo(game)}
  function startGame(){const character=data.characters.find(item=>item.id===document.getElementById('roleSelect').value);if(!character)return;game.procedure=document.getElementById('procedureSelect').value;game.mode=document.querySelector('#modeGrid .selected').dataset.mode;game.difficulty=document.querySelector('#difficultyGrid .selected')?.dataset.difficulty||'medium';game.mission=document.querySelector('#missionGrid .selected').dataset.mission;game.role=character.id;if(game.mission==='role'&&!character.playable&&character.reviewPlayable){game.procedure=character.procedure;ui.openReviewLab(character);return}if(game.mission==='role'&&!character.playable)return;if(game.mission==='random'){const mainIds=new Set(data.mainCharacterIds[game.procedure]||[]),playable=data.characters.filter(item=>item.playable&&item.procedure===game.procedure&&mainIds.has(item.id)).map(item=>item.id);game.role=playable[Math.floor(Math.random()*playable.length)];game.mission='role'}game.staticUnit=game.mission==='campaign'?false:Math.random()<.45;game.receiptHasDuesOut=game.mission==='campaign'||Math.random()<.5;game.transport=['Road','Rail','Post'][Math.floor(Math.random()*3)];Object.assign(game,{index:0,score:0,combo:0,lives:game.mode==='learn'?4:3,elapsed:0,penalty:0,completed:[],mistakes:0,running:true,paused:false,currentSpeed:game.player.speed,boosting:false,trail:[],trailClock:0,touchVector:{x:0,y:0},autoNavigation:null,situationGateKey:null});game.player.x=570;game.player.y=620;game.player.moving=false;game.startedAt=performance.now();game.lastTime=performance.now();generateRoute();setCargoForStep();document.getElementById('startOverlay').classList.add('hidden');document.getElementById('endOverlay').classList.add('hidden');ui.resetHandoffLog();ui.updateHUD(game);ui.updateObjective(game);ui.renderRoute(game);ui.showOfficeIntel(game.route[0],game.procedure);tone(420,.1);setTimeout(()=>tone(640,.12),100)}
  function quitGame(){game.running=false;game.paused=false;game.autoNavigation=null;game.touchVector={x:0,y:0};document.getElementById('miniOverlay').classList.add('hidden');document.getElementById('endOverlay').classList.add('hidden');document.getElementById('startOverlay').classList.remove('hidden');ui.selectCharacter(game.role)}
  function currentTarget(){return game.route[game.index]}
  function interact(){if(!game.running||game.paused)return;const nearby=map.nearestBuilding(game.player,game.procedure);if(!nearby){tone(180,.08,'square',.03);return}if(nearby.id!==currentTarget()){wrongOffice(nearby);return}ui.openOfficeGame(nearby.id)}
  function navigateToOffice(officeId){const office=map.building(officeId,game.procedure);if(!game.running||game.paused||!office)return;game.autoNavigation={officeId,target:map.center(office)};game.touchVector={x:0,y:0};ui.showOfficeIntel(officeId,game.procedure)}
  function cancelNavigation(){game.autoNavigation=null}
  function activateContingency(role,officeId){const character=data.characters.find(item=>item.id===role&&item.procedure===game.procedure);if(!character||!character.playable||character.route[0]!==officeId)return false;game.mission='role';game.role=role;game.campaignStages=[];game.characterStages=(data.characterStageEvents?.[role]||[]).map(stage=>({...stage}));game.route=[...character.route];game.index=0;game.completed=[];game.combo=0;game.autoNavigation=null;game.situationGateKey=`${role}:0:${officeId}`;setCargoForStep();ui.resetHandoffLog();ui.updateHUD(game);ui.updateObjective(game);ui.renderRoute(game);ui.showOfficeIntel(officeId,game.procedure);return true}
  function wrongOffice(office){game.lives--;game.combo=0;game.mistakes++;game.penalty+=game.mode==='learn'?6:10;tone(130,.18,'sawtooth',.05);ui.flash('#ff758c33');ui.updateHUD(game);ui.showBriefFeedback('Wrong office',`${office.label} is not the next control point for ${game.cargo.name}. The correct destination is ${map.building(currentTarget()).label}. ${data.officeWhy[currentTarget()]}`,false);if(game.lives<=0)setTimeout(()=>{ui.closeMini();finishMission(false)},600)}
  function completeStep(){const id=currentTarget(),next=game.route[game.index+1];ui.recordHandoff(game,id,next);game.completed.push(id);game.index++;game.combo++;game.score+=100+game.combo*15;tone(620,.08);setTimeout(()=>tone(820,.08),70);ui.flash('#62e7a333');if(game.index>=game.route.length){ui.updateHUD(game);setTimeout(()=>finishMission(true),400);return}setCargoForStep();ui.updateHUD(game);ui.updateObjective(game);ui.renderRoute(game)}
  function failMini(message){game.lives--;game.combo=0;game.mistakes++;game.penalty+=8;ui.updateHUD(game);tone(150,.18,'square',.05);const feedback=document.querySelector('#miniModal .feedback');if(feedback){feedback.textContent=message;feedback.style.borderColor='#a94c60'}if(game.lives<=0)setTimeout(()=>{ui.closeMini();finishMission(false)},600)}
  function finishMission(success){game.running=false;game.paused=false;ui.finishMission(game,success);tone(success?760:160,.22,success?'sine':'sawtooth',.06)}
  function update(delta){if(!game.running||game.paused)return;const player=game.player,keys=game.keys,touch=game.touchVector||{x:0,y:0};let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+touch.x,dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+touch.y;if(Math.hypot(touch.x,touch.y)>.08||keys.ArrowRight||keys.ArrowLeft||keys.ArrowUp||keys.ArrowDown||keys.w||keys.a||keys.s||keys.d)game.autoNavigation=null;if(!dx&&!dy&&game.autoNavigation){const offsetX=game.autoNavigation.target.x-player.x,offsetY=game.autoNavigation.target.y-player.y,distance=Math.hypot(offsetX,offsetY);if(distance<72){const destination=game.autoNavigation.officeId;game.autoNavigation=null;const arrived=map.building(destination,game.procedure);if(arrived)setTimeout(interact,0)}else{dx=offsetX/distance;dy=offsetY/distance}}game.boosting=!!(keys.Shift||keys.boost||game.autoNavigation);game.currentSpeed=player.speed*(game.boosting?1.42:1);player.moving=!!(dx||dy);if(player.moving){const magnitude=Math.hypot(dx,dy);dx/=magnitude;dy/=magnitude;player.facing=dx<0?-1:dx>0?1:player.facing;player.x+=dx*game.currentSpeed*delta;player.y+=dy*game.currentSpeed*delta;game.trailClock+=delta;if(game.trailClock>.035){game.trail.unshift({x:player.x,y:player.y,life:1,boost:game.boosting});game.trailClock=0}}for(const point of game.trail)point.life-=delta*3.8;game.trail=game.trail.filter(point=>point.life>0).slice(0,18);player.x=Math.max(18,Math.min(map.width-18,player.x));player.y=Math.max(18,Math.min(map.height-18,player.y));game.elapsed=(performance.now()-game.startedAt)/1000;ui.updateHUD(game);ui.setPrompt(map.nearestBuilding(player,game.procedure));ui.setCompass(game)}
  function loop(now){const delta=Math.min(.033,(now-game.lastTime)/1000||0);game.lastTime=now;update(delta);map.draw(game);requestAnimationFrame(loop)}

  return {game,tone,startGame,quitGame,interact,navigateToOffice,cancelNavigation,activateContingency,completeStep,failMini,finishMission,loop};
});
