(function attachMap(root, factory) {
  const api = factory(root.DepotData);
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.DepotMap = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createMap(data) {
  'use strict';
  const canvas = typeof document !== 'undefined' ? document.getElementById('game') : null;
  const ctx = canvas ? canvas.getContext('2d') : null;
  const width = canvas ? canvas.width : 1200;
  const height = canvas ? canvas.height : 675;
  let hoveredId=null;

  function building(id,procedure){const item=data.offices.find(candidate=>candidate.id===id);if(!item)return item;const layout=procedure&&data.mapLayouts&&data.mapLayouts[procedure]&&data.mapLayouts[procedure][id];return layout?{...item,...layout}:item}
  function center(item){return{x:item.x+item.w/2,y:item.y+item.h/2}}
  function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  function activeOffices(procedure){const ids=data.mapOfficeIds?data.mapOfficeIds[procedure]:data.offices.map(item=>item.id);return ids.map(id=>building(id,procedure)).filter(Boolean)}
  function nearestBuilding(player,procedure='Issue'){let best=null,bestDistance=Infinity;for(const item of activeOffices(procedure)){const next=distance(player,center(item));if(next<bestDistance){bestDistance=next;best=item}}return bestDistance<105?best:null}
  function buildingAt(point,procedure='Issue'){return activeOffices(procedure).find(item=>point.x>=item.x&&point.x<=item.x+item.w&&point.y>=item.y&&point.y<=item.y+item.h)||null}
  function setHovered(id){hoveredId=id||null}

  function drawGround(){const time=performance.now()/1000,ground=ctx.createLinearGradient(0,0,width,height);ground.addColorStop(0,'#073a3b');ground.addColorStop(.52,'#102f31');ground.addColorStop(1,'#071825');ctx.fillStyle=ground;ctx.fillRect(0,0,width,height);ctx.strokeStyle='#5de5cf17';ctx.lineWidth=1;for(let x=0;x<width;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke()}for(let y=0;y<height;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}const scanY=(time*95)%height,scan=ctx.createLinearGradient(0,scanY-38,0,scanY+38);scan.addColorStop(0,'#45f5ff00');scan.addColorStop(.5,'#45f5ff16');scan.addColorStop(1,'#45f5ff00');ctx.fillStyle=scan;ctx.fillRect(0,scanY-38,width,76);ctx.strokeStyle='#5fe4d188';ctx.lineWidth=4;ctx.shadowColor='#42d9ff';ctx.shadowBlur=8;ctx.strokeRect(8,8,width-16,height-16);ctx.shadowBlur=0;ctx.strokeStyle='#9a7cff44';ctx.lineWidth=1;ctx.strokeRect(14,14,width-28,height-28)}
  function drawRoads(){const road=ctx.createLinearGradient(0,0,0,height);road.addColorStop(0,'#263946');road.addColorStop(1,'#1b2d38');ctx.fillStyle=road;[[0,330,width,108],[535,0,95,height],[0,460,220,65],[780,455,420,75]].forEach(rect=>ctx.fillRect(...rect));ctx.strokeStyle='#76e7f777';ctx.setLineDash([22,18]);ctx.lineWidth=2;ctx.shadowColor='#42d9ff';ctx.shadowBlur=5;ctx.beginPath();ctx.moveTo(0,384);ctx.lineTo(width,384);ctx.moveTo(582,0);ctx.lineTo(582,height);ctx.stroke();ctx.shadowBlur=0;ctx.setLineDash([])}
  function drawDecor(){const time=performance.now()/1000,truckX=(time*55)%(width+140)-140;ctx.fillStyle='#1d2b31';ctx.fillRect(truckX,348,86,36);ctx.fillStyle='#6b7a46';ctx.fillRect(truckX+12,337,54,28);ctx.fillStyle='#111';ctx.beginPath();ctx.arc(truckX+18,386,9,0,Math.PI*2);ctx.arc(truckX+70,386,9,0,Math.PI*2);ctx.fill();const forkX=420+Math.sin(time*.8)*55;ctx.fillStyle='#d4a62a';ctx.fillRect(forkX,442,38,26);ctx.fillStyle='#161d22';ctx.fillRect(forkX+28,430,5,40);ctx.beginPath();ctx.arc(forkX+8,470,7,0,Math.PI*2);ctx.arc(forkX+30,470,7,0,Math.PI*2);ctx.fill();[[198,155],[375,520],[1115,165],[835,440],[1120,430]].forEach(([x,y])=>{ctx.fillStyle='#543d25';ctx.fillRect(x-4,y,8,20);ctx.fillStyle='#2c6d3f';ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fill()})}
  function drawBuildings(game){const target=game.route[game.index],pulse=.5+.5*Math.sin(performance.now()/260);for(const item of activeOffices(game.procedure||'Issue')){const isTarget=game.running&&item.id===target,complete=game.completed.includes(item.id),hovered=item.id===hoveredId,gradient=ctx.createLinearGradient(item.x,item.y,item.x,item.y+item.h);gradient.addColorStop(0,item.color);gradient.addColorStop(1,'#071722');ctx.save();if((isTarget&&game.mode!=='exam')||hovered){ctx.shadowColor=hovered?'#55efff':'#ffd76f';ctx.shadowBlur=hovered?24:18+pulse*12}ctx.beginPath();ctx.roundRect(item.x,item.y,item.w,item.h,10);ctx.fillStyle=gradient;ctx.fill();ctx.strokeStyle=hovered?'#7ff4ff':isTarget&&game.mode!=='exam'?'#ffd76f':complete?'#4fffc0':'#78b6c8';ctx.lineWidth=hovered||isTarget&&game.mode!=='exam'?4:2;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=hovered?'#7ff4ff':isTarget&&game.mode!=='exam'?'#ffd76f':complete?'#4fffc0':'#42d9ff';ctx.fillRect(item.x+10,item.y+8,Math.max(28,item.w*.28),3);ctx.fillStyle='#06131c';ctx.beginPath();ctx.roundRect(item.x+item.w/2-22,item.y+item.h-35,44,35,7);ctx.fill();ctx.fillStyle='#f3fbff';ctx.textAlign='center';ctx.font='700 12px Inter, Segoe UI';ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.fillText(item.label,item.x+item.w/2,item.y+24);ctx.shadowBlur=0;ctx.font='32px Segoe UI Emoji';ctx.fillText(item.icon,item.x+item.w/2,item.y+62);ctx.fillStyle=hovered?'#bff9ff':'#7da7b8';ctx.font='700 8px Inter, Segoe UI';ctx.fillText(hovered?'OPEN DOSSIER':`SECTION ${String(activeOffices(game.procedure||'Issue').indexOf(item)+1).padStart(2,'0')}`,item.x+item.w/2,item.y+item.h-8);if(complete){ctx.fillStyle='#4fffc0';ctx.shadowColor='#4fffc0';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(item.x+item.w-14,item.y+14,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#043127';ctx.font='bold 12px Segoe UI';ctx.fillText('✓',item.x+item.w-14,item.y+18)}ctx.restore()}}
  function drawPlayer(game){const player=game.player,time=performance.now()/1000;for(const point of game.trail||[]){ctx.save();ctx.globalAlpha=point.life*.34;ctx.fillStyle=point.boost?'#a584ff':'#42d9ff';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(point.x,point.y+9,3+point.life*5,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.save();ctx.translate(player.x,player.y);ctx.scale(player.facing||1,1);ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(0,16,22,8,0,0,Math.PI*2);ctx.fill();if(player.moving){ctx.strokeStyle=game.boosting?'#a584ff':'#42d9ff';ctx.globalAlpha=.7;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-8,11);ctx.lineTo(-24,11+Math.sin(time*18)*3);ctx.stroke();ctx.globalAlpha=1}const stride=player.moving?Math.sin(time*18)*5:0;ctx.strokeStyle='#152430';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-6,8);ctx.lineTo(-8-stride,22);ctx.moveTo(6,8);ctx.lineTo(8+stride,22);ctx.stroke();const suit=ctx.createLinearGradient(-15,-17,15,14);suit.addColorStop(0,'#4d7650');suit.addColorStop(1,'#203f43');ctx.fillStyle=suit;ctx.shadowColor=game.boosting?'#a584ff':'#42d9ff';ctx.shadowBlur=game.boosting?16:8;ctx.beginPath();ctx.roundRect(-15,-17,30,31,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#d5a77a';ctx.beginPath();ctx.arc(0,-26,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#264027';ctx.fillRect(-12,-37,24,8);ctx.fillStyle='#8d5a2d';ctx.fillRect(12,-12,14,23);ctx.fillStyle='#55efff';ctx.fillRect(-6,-10,12,3);ctx.fillStyle='#fff';ctx.font='bold 9px Segoe UI';ctx.textAlign='center';ctx.scale(player.facing||1,1);ctx.fillText(game.cargo.name.substring(0,4),19*(player.facing||1),2);ctx.restore()}
  function drawTargetArrow(game){if(!game.running||game.mode==='exam')return;const target=building(game.route[game.index],game.procedure);if(!target)return;const targetCenter=center(target);ctx.strokeStyle=game.mode==='learn'?'#ffd76f':'#69c9ff';ctx.lineWidth=3;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(game.player.x,game.player.y);ctx.lineTo(targetCenter.x,targetCenter.y);ctx.stroke();ctx.setLineDash([])}
  function draw(game){if(!ctx)return;ctx.clearRect(0,0,width,height);drawGround();drawRoads();drawDecor();drawBuildings(game);drawPlayer(game);drawTargetArrow(game)}

  return {canvas,ctx,width,height,building,center,activeOffices,nearestBuilding,buildingAt,setHovered,draw};
});
